-- AlterTable
ALTER TABLE `UserCar` MODIFY `speed` DECIMAL(4, 2) NOT NULL DEFAULT 0,
    MODIFY `handling` DECIMAL(4, 2) NOT NULL DEFAULT 0,
    MODIFY `acceleration` DECIMAL(4, 2) NOT NULL DEFAULT 0,
    MODIFY `launch` DECIMAL(4, 2) NOT NULL DEFAULT 0,
    MODIFY `breaking` DECIMAL(4, 2) NOT NULL DEFAULT 0,
    MODIFY `offroad` DECIMAL(4, 2) NOT NULL DEFAULT 0;
